In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
#Creating an array
x=np.array([[1,2,4],[4,7,8]])
x

array([[1, 2, 4],
       [4, 7, 8]])

In [5]:
np.shape(x)

(2, 3)

In [6]:
np.size(x)

6

In [7]:
x.itemsize

4

In [8]:
#reshape
x.reshape(3,2)

array([[1, 2],
       [4, 4],
       [7, 8]])

In [9]:
x.reshape(1,6)

array([[1, 2, 4, 4, 7, 8]])

In [10]:
#slicing 
x[0]

array([1, 2, 4])

In [12]:
x[0:2]

array([[1, 2, 4],
       [4, 7, 8]])

In [13]:
x[0,1]

2

In [14]:
x[1,0]

4

In [15]:
x[1]

array([4, 7, 8])

In [16]:
x

array([[1, 2, 4],
       [4, 7, 8]])

In [17]:
x[0:,0]

array([1, 4])

In [18]:
x[:,-1]

array([4, 8])

In [19]:
x[:,2]

array([4, 8])

In [23]:
x[::2,::2]

array([[1, 4]])

In [26]:
x[:,0::2]

array([[1, 4],
       [4, 8]])

In [27]:
k=np.array([[1,2,3],[4,5,6],[7,8,9]])
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
k[:,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [30]:
k[:,:2:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
k[:2:,::]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
k.max()

9

In [33]:
k.min()

1

In [34]:
k.sum()

45

In [35]:
k.mean()   #avg

5.0

In [37]:
k.min(axis=0)

array([1, 2, 3])

In [38]:
k.sum(axis=0)

array([12, 15, 18])

In [39]:
k.min(axis=1)

array([1, 4, 7])

In [40]:
k.max(axis=0)

array([7, 8, 9])

In [42]:
# whole data which we are guiving will be printed on vertical format
np.vstack((k,x))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 4],
       [4, 7, 8]])

In [44]:
np.hstack((k))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.tan(k)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [47]:
np.cos(k)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

### Pandas

In [7]:
import pandas as pd

In [5]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [ ]:
#creating a series data type

In [10]:
s=pd.Series([1,3,67,5,9,8])
s

0     1
1     3
2    67
3     5
4     9
5     8
dtype: int64

In [12]:
s=pd.Series([1,3,67,5,9,8],index=['y','u','k','r','d','a'])
s

y     1
u     3
k    67
r     5
d     9
a     8
dtype: int64

In [33]:
v1=[1,6,9]
v2=[6,9,0]
df=pd.DataFrame({'x':v1,'y':v2,})
df

x  y
0  1  6
1  6  9
2  9  0

### Operations in pandas

In [ ]:
** Slicing
** Merging and joining
** Concatination
** Changing the index
** Changiung column header
** Data munging

### Slicing in dataframe

In [22]:
df.tail()

x  y
0  1  6
1  6  9
2  9  0

In [16]:
df.tail(1)

x  y
2  9  0

#### Merging and Joining

In [29]:
v1=[0,6,6]
v2=[66,45,6]
v3=[90,8,99]
df1=pd.DataFrame({'x':v1,'y':v2,'z':v3})
df1

x   y   z
0  0  66  90
1  6  45   8
2  6   6  99

In [24]:
pd.merge(df1,df)

Empty DataFrame
Columns: [x, y]
Index: []

In [34]:
j=df.join(df1)
j

ValueError: columns overlap but no suffix specified: Index(['x', 'y'], dtype='object')

In [42]:
d=[[2,3,4],[6,7,9,99],[7,9,3],[8,9,4]]

In [43]:
f1=pd.DataFrame(d,columns=["x",'y','z','z1'],index=[1,2,3,4])

In [44]:
f1

x  y  z    z1
1  2  3  4   NaN
2  6  7  9  99.0
3  7  9  3   NaN
4  8  9  4   NaN

In [45]:
d1=[[3,4,6],[6,7,8,9],[8,9,6,4],[8,9,4]]
f2=pd.DataFrame(d1,columns=["x",'y','z','z1'])
f2

x  y  z   z1
0  3  4  6  NaN
1  6  7  8  9.0
2  8  9  6  4.0
3  8  9  4  NaN

In [46]:
m=pd.merge(f1,f2)
m

x  y  z  z1
0  8  9  4 NaN

In [53]:
x=[[1,2,3],[4,5,6]]
f3=pd.DataFrame(x,columns=['y1','y2','y3'],index=['a','b'])
f3

y1  y2  y3
a   1   2   3
b   4   5   6

In [51]:
f4=pd.DataFrame({'name':[6,9,77],'gender':[1,7,98]})
f4

name  gender
0     6       1
1     9       7
2    77      98

In [54]:
j=f3.join(f4)
j

y1  y2  y3  name  gender
a   1   2   3   NaN     NaN
b   4   5   6   NaN     NaN

In [55]:
# Concat 
c=pd.concat([f3,f2])
c

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


x    y   y1   y2   y3    z   z1
a  NaN  NaN  1.0  2.0  3.0  NaN  NaN
b  NaN  NaN  4.0  5.0  6.0  NaN  NaN
0  3.0  4.0  NaN  NaN  NaN  6.0  NaN
1  6.0  7.0  NaN  NaN  NaN  8.0  9.0
2  8.0  9.0  NaN  NaN  NaN  6.0  4.0
3  8.0  9.0  NaN  NaN  NaN  4.0  NaN

In [56]:
c.isnull()

x      y     y1     y2     y3      z     z1
a   True   True  False  False  False   True   True
b   True   True  False  False  False   True   True
0  False  False   True   True   True  False   True
1  False  False   True   True   True  False  False
2  False  False   True   True   True  False  False
3  False  False   True   True   True  False   True

In [57]:
c.notnull()

x      y     y1     y2     y3      z     z1
a  False  False   True   True   True  False  False
b  False  False   True   True   True  False  False
0   True   True  False  False  False   True  False
1   True   True  False  False  False   True   True
2   True   True  False  False  False   True   True
3   True   True  False  False  False   True  False

In [58]:
f3+f2

x   y  y1  y2  y3   z  z1
a NaN NaN NaN NaN NaN NaN NaN
b NaN NaN NaN NaN NaN NaN NaN
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN

In [60]:
#index changing
c1=pd.DataFrame({1:[1,2,3],2:[4,5,6],'i':['x','y','z']})
c1.set_index('i')

1  2
i      
x  1  4
y  2  5
z  3  6

In [61]:
#changing the column headers
c1.rename(columns={1:'a',2:'b'})

a  b  i
0  1  4  x
1  2  5  y
2  3  6  z

In [63]:
dd=pd.read_csv("number.csv")  #data munging
dd

x y z
0  5 0 41
1   3 9 2
2  4 7 88
3   5 6 1