In [ ]:
#elements accessing row/column
#loc and iloc----->location and index location

In [5]:
import pandas as pd
df=pd.DataFrame({"name":['pinky','ponky','gumky'],"roll-numbers":[525,546,556],"branch":['cse','ece','civil']})
df

name  roll-numbers branch
0  pinky           525    cse
1  ponky           546    ece
2  gumky           556  civil

In [6]:
import pandas as pd
df=pd.DataFrame({"name":['pinky','ponky','gumky'],"roll-numbers":[525,546,556],"branch":['cse','ece','civil']},index=[7,8,9])
df

name  roll-numbers branch
7  pinky           525    cse
8  ponky           546    ece
9  gumky           556  civil

In [7]:
df.loc[8]

name            ponky
roll-numbers      546
branch            ece
Name: 8, dtype: object

In [8]:
df.loc[7]["branch"]

'cse'

In [11]:
df.iloc[0]   #we access the data  by using index name

name            pinky
roll-numbers      525
branch            cse
Name: 7, dtype: object

In [12]:
df.iloc[1]['name']

'ponky'

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 7 to 9
Data columns (total 3 columns):
name            3 non-null object
roll-numbers    3 non-null int64
branch          3 non-null object
dtypes: int64(1), object(2)
memory usage: 176.0+ bytes


In [20]:
df.count()  #count non-NA cells for each columns and rows

name            3
roll-numbers    3
branch          3
dtype: int64

In [21]:
df.describe()

roll-numbers
count      3.000000
mean     542.333333
std       15.821926
min      525.000000
25%      535.500000
50%      546.000000
75%      551.000000
max      556.000000

In [22]:
df.count(axis="rows")

name            3
roll-numbers    3
branch          3
dtype: int64

In [23]:
df.count(axis="columns")

7    3
8    3
9    3
dtype: int64

In [24]:
df.set_index(["roll-numbers"])

name branch
roll-numbers              
525           pinky    cse
546           ponky    ece
556           gumky  civil

In [25]:
df.set_index(["roll-numbers","branch"])

name
roll-numbers branch       
525          cse     pinky
546          ece     ponky
556          civil   gumky

In [27]:
s=pd.Series([3,566,78,54,4])
s

0      3
1    566
2     78
3     54
4      4
dtype: int64

In [28]:
s.describe()

count      5.000000
mean     141.000000
std      239.779065
min        3.000000
25%        4.000000
50%       54.000000
75%       78.000000
max      566.000000
dtype: float64

In [29]:
s.count()

5

In [30]:
import numpy as np

In [37]:
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

In [38]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
d=pd.DataFrame(np.arange(12).reshape(3,4))
d

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [43]:
d=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])   #columns replace with giving values
d

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [45]:
d=pd.DataFrame(np.arange(12).reshape(4,3),index=['a','b','c','d'])   #columns replace with giving values
d

0   1   2
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [46]:
h=np.arange(20)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
h.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
o=pd.DataFrame(np.arange(20).reshape(5,4),columns=list('abcd'))   #columns replace with giving values
o

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [49]:
o.loc[1,'b']=np.NaN

In [50]:
o

a     b   c   d
0   0   1.0   2   3
1   4   NaN   6   7
2   8   9.0  10  11
3  12  13.0  14  15
4  16  17.0  18  19

In [60]:
dm=o.add(df)
dm

a   b branch   c   d name  roll-numbers
0 NaN NaN    NaN NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN NaN  NaN           NaN
4 NaN NaN    NaN NaN NaN  NaN           NaN
7 NaN NaN    NaN NaN NaN  NaN           NaN
8 NaN NaN    NaN NaN NaN  NaN           NaN
9 NaN NaN    NaN NaN NaN  NaN           NaN

In [61]:
dm.fill_value=

In [62]:
dm

a   b branch   c   d name  roll-numbers
0 NaN NaN    NaN NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN NaN  NaN           NaN
4 NaN NaN    NaN NaN NaN  NaN           NaN
7 NaN NaN    NaN NaN NaN  NaN           NaN
8 NaN NaN    NaN NaN NaN  NaN           NaN
9 NaN NaN    NaN NaN NaN  NaN           NaN

In [63]:
np.random.rand(2,5)

array([[0.17415976, 0.07850776, 0.61203228, 0.22001713, 0.07873744],
       [0.2179156 , 0.68764194, 0.35259859, 0.93101907, 0.59420952]])

In [64]:
np.random.randn(2,5)

array([[ 1.61434852, -1.25986352,  1.23579001, -0.54870024,  0.7286321 ],
       [-0.32069935,  0.71598533,  0.15948368,  0.09857835, -0.55001747]])

In [65]:
#Creating dataframe with random values
r=pd.DataFrame(np.random.randn(3,10))
r

0         1         2         3         4         5         6  \
0  0.148701  1.723213  0.824019 -0.897777 -0.718107 -0.094466  1.423789   
1 -0.533609 -0.007114 -0.432092 -0.031271 -1.160691 -0.658039  0.515958   
2  1.155667  0.627915  0.525557  0.763246 -0.875255  0.044388 -0.217060   

          7         8         9  
0 -0.676466 -1.464776 -0.101713  
1 -0.600000 -1.901669  0.035694  
2 -0.805553  1.084116 -0.245109

In [66]:
# generating index and columns
r=pd.DataFrame(np.random.randn(3,4),index=['c','a','b'],columns=['s1','s2','s3','s4'])
r

s1        s2        s3        s4
c -1.104147  1.902857 -0.417964 -0.115585
a -0.281703 -1.620111  0.264407  0.559977
b -0.446216 -1.731025 -0.101466  2.680941

In [67]:
r.index=['a','b','c']   #to set index to the present data

In [68]:
r

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941

In [70]:
#to reindex the present index
r1=r.reindex(['a','b','c','d'])
r1

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941
d       NaN       NaN       NaN       NaN

In [74]:
r1.isnull()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True

In [76]:
r1.isnull().sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [77]:
r1.dropna()   # to remove or drop the null values

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941

In [78]:
r1.fillna(2)  #filling the null values by using the any value

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941
d  2.000000  2.000000  2.000000  2.000000

In [82]:
# to fill nullvalues by backward or front
r1.fillna(method='bfill',axis=0).fillna(1)
#In the backward fill the data which we have given to fill will fill the null values

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941
d  1.000000  1.000000  1.000000  1.000000

In [83]:
# to fill nullvalues by backward or front
r1.fillna(method='ffill',axis=0).fillna(1)   #for fforward fill the above data will fill in the null values

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941
d -0.446216 -1.731025 -0.101466  2.680941

In [86]:
#To check in a particular column
pd.isna(r1['s3'])

a    False
b    False
c    False
d     True
Name: s3, dtype: bool

In [87]:
pd.isna(r1['s1'])

a    False
b    False
c    False
d     True
Name: s1, dtype: bool

In [88]:
r1.replace(2.680941,9999)  #for replacing the data

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941
d       NaN       NaN       NaN       NaN

In [89]:
#index Sorting and ranking 
r1

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
b -0.281703 -1.620111  0.264407  0.559977
c -0.446216 -1.731025 -0.101466  2.680941
d       NaN       NaN       NaN       NaN

In [93]:
e=r1.reindex(['d','a','c','z'])
e

s1        s2        s3        s4
d       NaN       NaN       NaN       NaN
a -1.104147  1.902857 -0.417964 -0.115585
c -0.446216 -1.731025 -0.101466  2.680941
z       NaN       NaN       NaN       NaN

In [94]:
# sorting the index
e.sort_index()

s1        s2        s3        s4
a -1.104147  1.902857 -0.417964 -0.115585
c -0.446216 -1.731025 -0.101466  2.680941
d       NaN       NaN       NaN       NaN
z       NaN       NaN       NaN       NaN

In [98]:
r1.columns=['s3','s6','s2','s4']
r1

['s3', 's6', 's2', 's4']

In [100]:
r1.sort_index(axis=1)

s2        s3        s4        s6
a -0.417964 -1.104147 -0.115585  1.902857
b  0.264407 -0.281703  0.559977 -1.620111
c -0.101466 -0.446216  2.680941 -1.731025
d       NaN       NaN       NaN       NaN

In [102]:
#groupby
animal=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','uuu','zoo','uu','oo'],
                     'features':['r','t','u','e','g']})
animal

name place features
0  dog   zoo        r
1  cat   uuu        t
2  cow   zoo        u
3  dog    uu        e
4  cat    oo        g

In [103]:
animal.groupby('name')

In [104]:
animal.groupby('name').sum()

place features
name                
cat   uuuoo       tg
cow     zoo        u
dog   zoouu       re

In [105]:
animal.groupby('name').count()

place  features
name                 
cat       2         2
cow       1         1
dog       2         2

In [107]:
#Ranking concept

animal2=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','uuu','zoo','uu','oo'],
                     'no-legs':[4,2,3,2,np.nan]})
animal2

name place  no-legs
0  dog   zoo      4.0
1  cat   uuu      2.0
2  cow   zoo      3.0
3  dog    uu      2.0
4  cat    oo      NaN

In [109]:
animal2['rank1']=animal2['no-legs'].rank()
animal2

name place  no-legs  rank1
0  dog   zoo      4.0    4.0
1  cat   uuu      2.0    1.5
2  cow   zoo      3.0    3.0
3  dog    uu      2.0    1.5
4  cat    oo      NaN    NaN

In [110]:
animal2['max-rank1']=animal2['no-legs'].rank(method="max")
animal2

name place  no-legs  rank1  max-rank1
0  dog   zoo      4.0    4.0        4.0
1  cat   uuu      2.0    1.5        2.0
2  cow   zoo      3.0    3.0        3.0
3  dog    uu      2.0    1.5        2.0
4  cat    oo      NaN    NaN        NaN

In [111]:
animal2['first_rank1']=animal2['no-legs'].rank(method="first")
animal2

name place  no-legs  rank1  max-rank1  first_rank1
0  dog   zoo      4.0    4.0        4.0          4.0
1  cat   uuu      2.0    1.5        2.0          1.0
2  cow   zoo      3.0    3.0        3.0          3.0
3  dog    uu      2.0    1.5        2.0          2.0
4  cat    oo      NaN    NaN        NaN          NaN

In [112]:
animal2['non-rank']=animal2['no-legs'].rank(na_option="bottom")
animal2

name place  no-legs  rank1  max-rank1  first_rank1  non-rank
0  dog   zoo      4.0    4.0        4.0          4.0       4.0
1  cat   uuu      2.0    1.5        2.0          1.0       1.5
2  cow   zoo      3.0    3.0        3.0          3.0       3.0
3  dog    uu      2.0    1.5        2.0          2.0       1.5
4  cat    oo      NaN    NaN        NaN          NaN       5.0

In [113]:
animal2["pct-rank"]=animal2['no-legs'].rank(pct=True)
animal2

name place  no-legs  rank1  max-rank1  first_rank1  non-rank  pct-rank
0  dog   zoo      4.0    4.0        4.0          4.0       4.0     1.000
1  cat   uuu      2.0    1.5        2.0          1.0       1.5     0.375
2  cow   zoo      3.0    3.0        3.0          3.0       3.0     0.750
3  dog    uu      2.0    1.5        2.0          2.0       1.5     0.375
4  cat    oo      NaN    NaN        NaN          NaN       5.0       NaN

In [116]:
#Categorise
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [117]:
data_frame["cc"]=data_frame['y'].astype('category')

In [119]:
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [120]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [121]:
data_frame["cc"].cat.categories=["good","bad","worst","verybad","gcgfdg"]
data_frame

x   y       cc
0  1   6     good
1  2   7      bad
2  3   8    worst
3  4   9  verybad
4  5  10   gcgfdg

In [122]:
data_frame.sort_values('cc')

x   y       cc
0  1   6     good
1  2   7      bad
2  3   8    worst
3  4   9  verybad
4  5  10   gcgfdg

In [127]:
#reading the data 
df=pd.read_table("data1.txt")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


a b c
0  1 2 3
1  4 5 6
2  7 8 9

In [128]:
#reading the data 
df=pd.read_table("ex1.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [129]:
#reading the data 
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead.
  


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [130]:
#reading the data 
df=pd.read_csv("ex2.csv")
df

1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [131]:
df.head(1)

1  2  3  4  hello
0  5  6  7  8  world

In [132]:
df.tail(1)

1   2   3   4 hello
1  9  10  11  12   foo