##  Numpy
1. numpy used for the scientific computing
2.numerical python

In [5]:
import numpy as n
a=n.array([[1,2,3],[4,5,6]])
#shape(row,column)---->(2,3)
#dimensional-------2
#rank--------2
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(a)

numpy.ndarray

In [7]:
dir(n)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [8]:
a.ndim

2

In [9]:
a.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [12]:
y=n.array([[0.87,8.97,0.1],
          [8.9,6.6,89]])
y

array([[ 0.87,  8.97,  0.1 ],
       [ 8.9 ,  6.6 , 89.  ]])

In [14]:
#creating array with the type float
a=n.array([[1,2,3],[4,5,6]],dtype='float')
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
#creating an array with the complex 
n.array([[1,2,33],[4,5,78]],dtype='complex')

array([[ 1.+0.j,  2.+0.j, 33.+0.j],
       [ 4.+0.j,  5.+0.j, 78.+0.j]])

In [19]:
#creating an array with tuples
g=n.array(((22,33,44,),(55,76,5)))
g

array([[22, 33, 44],
       [55, 76,  5]])

In [22]:
n.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
n.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
n.ones((5,6),dtype='int')   #it will work only for ones and zeros   # for another values we use full method given below

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [28]:
s=n.full((2,3),5,dtype="int")
s                                      #

array([[5, 5, 5],
       [5, 5, 5]])

In [30]:
# To create an array with random values
n.empty(4)

array([ 8.83091570e-312,  7.54071371e+173, -3.51332747e-289,
        7.23154601e+173])

In [32]:
n.empty((4,5),dtype="int")

array([[ 724952424,        416,         46,          0,          0],
       [         0,          0,          0,          0,    6029411],
       [1868767867,  975332708, 1697541666, 2037674093,  741615656],
       [ 573122869, 2019893804, 1953850213, 1601073001, 1853189987]])

In [39]:
j=n.array([[456,76,8],[45,87,9],[67,9,8]])
j

array([[456,  76,   8],
       [ 45,  87,   9],
       [ 67,   9,   8]])

In [40]:
j.max()

456

In [41]:
j.min()

8

In [42]:
j.max(axis=0) #row wise maximum values

array([456,  87,   9])

In [43]:
j.min(axis=0)  #row wise minimun value axis =0

array([45,  9,  8])

In [44]:
j.min(axis=1)  #column wise minimum values

array([8, 9, 8])

In [47]:
j.max(axis=1)   #column wise maximum value

array([456,  87,  67])

In [49]:
j.cumsum(axis=0) #column wise cummulative sum

array([[456,  76,   8],
       [501, 163,  17],
       [568, 172,  25]], dtype=int32)

In [50]:
j.cumsum(axis=1) #row wise cummumlative sum

array([[456, 532, 540],
       [ 45, 132, 141],
       [ 67,  76,  84]], dtype=int32)

In [51]:
#To find the transpose
j.T

array([[456,  45,  67],
       [ 76,  87,   9],
       [  8,   9,   8]])

In [54]:
r=n.array([[3,.7,8]],dtype="int")
r

array([[3, 0, 8]])

In [55]:
r+1

array([[4, 1, 9]])

In [56]:
r**2

array([[ 9,  0, 64]], dtype=int32)

In [57]:
r-2

array([[ 1, -2,  6]])

In [60]:
s=n.array([[4,6],[6,87],[7,9]])
k=n.array([[5,7],[8,9],[6,4]])
print(s)
print(k)

[[ 4  6]
 [ 6 87]
 [ 7  9]]
[[5 7]
 [8 9]
 [6 4]]


In [61]:
s+k

array([[ 9, 13],
       [14, 96],
       [13, 13]])

In [62]:
s-k

array([[-1, -1],
       [-2, 78],
       [ 1,  5]])

In [63]:
s**k

array([[     1024,    279936],
       [  1679616, 962091543],
       [   117649,      6561]], dtype=int32)

In [64]:
s*k

array([[ 20,  42],
       [ 48, 783],
       [ 42,  36]])

In [65]:
s/k

array([[0.8       , 0.85714286],
       [0.75      , 9.66666667],
       [1.16666667, 2.25      ]])

In [66]:
s//k

array([[0, 0],
       [0, 9],
       [1, 2]], dtype=int32)

In [69]:
n.add(s,k)

array([[ 9, 13],
       [14, 96],
       [13, 13]])

In [70]:
n.subtract(s,k)

array([[-1, -1],
       [-2, 78],
       [ 1,  5]])

In [71]:
n.multiply(s,k)

array([[ 20,  42],
       [ 48, 783],
       [ 42,  36]])

In [72]:
n.divide(s,k)

array([[0.8       , 0.85714286],
       [0.75      , 9.66666667],
       [1.16666667, 2.25      ]])

In [76]:
y=n.array([[5,7,8]])
n.sin(y)

array([[-0.95892427,  0.6569866 ,  0.98935825]])

In [77]:
n.sqrt(y)

array([[2.23606798, 2.64575131, 2.82842712]])

## creating an array using range functions


In [80]:
#n.arange(start,stop,step)
u=n.arange(2,7)
u

array([2, 3, 4, 5, 6])

In [82]:
n.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
n.arange(10,40,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [84]:
a=n.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
n.arange(10,20).reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [90]:
n.arange(10,1,-1).reshape(3,3)

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [94]:
n.linspace(1,2,5).reshape(5,1)

array([[1.  ],
       [1.25],
       [1.5 ],
       [1.75],
       [2.  ]])

In [96]:
d=n.array([[1,2,3],[3,4,5]])
d.resize(3,2)
d

array([[1, 2],
       [3, 3],
       [4, 5]])

## Iterating over the array

In [99]:
a=n.array([[1,2,3],[4,5,8],[4,5,6]])
for i in iter(a[0]):
    print(i)

1
2
3


In [100]:
a.flatten('c')                   #row wise

array([1, 2, 3, 4, 5, 8, 4, 5, 6])

In [102]:
a.flatten('f')                     #column wise

array([1, 4, 4, 2, 5, 5, 3, 8, 6])

### Indexing

In [103]:
a

array([[1, 2, 3],
       [4, 5, 8],
       [4, 5, 6]])

In [104]:
a[0][0]

1

In [105]:
a[1][1]

5

In [110]:
a=n.eye(3,5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [109]:
n.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
n.diag(n.arange(5,9))

array([[5, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [112]:
n.diag(n.arange(10,30,2)).reshape(5,20)

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 20,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 24,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 26,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0, 28]])

### slicing

In [114]:
a=n.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
#from 4 index to last
print(a[4::])
#from 0 to 4
print(a[:5:])
#from index 4(excluded) up to 7 (exclud)


[4 5 6 7 8 9]
[0 1 2 3 4]


In [119]:
a=n.array([[1,2,3,8],[4,5,6,3],[8,9,4,5],[6,9,2,1]])
a

array([[1, 2, 3, 8],
       [4, 5, 6, 3],
       [8, 9, 4, 5],
       [6, 9, 2, 1]])

In [122]:
a[0:1,0:1]

array([[1]])

In [124]:
a[1:3:]

array([[4, 5, 6, 3],
       [8, 9, 4, 5]])

In [126]:
a[1:2,1:3]

array([[5, 6]])

In [127]:
a[1:3,1:3]

array([[5, 6],
       [9, 4]])

In [128]:
a

array([[1, 2, 3, 8],
       [4, 5, 6, 3],
       [8, 9, 4, 5],
       [6, 9, 2, 1]])

In [130]:
a[3:,2:]

array([[2, 1]])

In [138]:
a[0::3,0:4:3]

array([[1, 8],
       [6, 1]])

In [148]:
a[1:4:2,0:3:2]

array([[4, 6],
       [6, 2]])

In [149]:
a=n.array([['fyf','tgh','fghf'],['tcgff','gyfgy','yghk']])
a

array([['fyf', 'tgh', 'fghf'],
       ['tcgff', 'gyfgy', 'yghk']], dtype='<U5')

In [150]:
for i in iter(a):
    print(i)

['fyf' 'tgh' 'fghf']
['tcgff' 'gyfgy' 'yghk']


In [151]:
for i in iter(a):
    print(i[0])

fyf
tcgff


In [152]:
for i in iter(a):
    print(n.char.upper(i))

['FYF' 'TGH' 'FGHF']
['TCGFF' 'GYFGY' 'YGHK']


## Linear Algebra
### Rank ,det,trace,inverse
#### Eigen values,eigen vectors
##### matrix and vector products

In [163]:
from numpy import linalg as l
k=n.array([[1,4,6],[4,8,9],[9,1,6]])
print(k)
#To find the rank
print(l.matrix_rank(k))
#To find the trace of a matrix
print(n.trace(k))
#To find the det of a given matrix
print(l.det(k))
#To find the inverse of a given matrix
print(l.inv(k))
#To find the power of a matrix
print(l.matrix_power(k,2))

[[1 4 6]
 [4 8 9]
 [9 1 6]]
3
15
-141.00000000000003
[[-0.27659574  0.12765957  0.08510638]
 [-0.40425532  0.34042553 -0.10638298]
 [ 0.4822695  -0.24822695  0.05673759]]
[[ 71  42  78]
 [117  89 150]
 [ 67  50  99]]


## Eigen values and eigen vectors

In [165]:
a=n.array([[1,2j,],[4,8j]])
a

array([[1.+0.j, 0.+2.j],
       [4.+0.j, 0.+8.j]])

In [169]:
b,c=l.eigh(a)
print(b)       #eigen values
print(c)       #eigen vectors

[-3.53112887  4.53112887]
[[ 0.66180256+0.j -0.74967818-0.j]
 [-0.74967818+0.j -0.66180256-0.j]]


In [175]:
a=n.diag((1,2,3))
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [176]:
b,c=l.eigh(a)
print(b)       #eigen values
print(c)       #eigen vectors

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Matrix and vector products

In [178]:
# Dot product
a=1
b=2
print(n.dot(a,b))   #dot product of scalar values
a1=1+5j
b1=2+6j
print(n.dot(a1,b1))   #dot product of vector values


2
(-28+16j)


In [179]:
# To find the dot products of conjugate vectors
print(n.vdot(a1,b1))

(32-4j)


 ## Pandas
 ##### * data processing and for analysis we use pandas
 ##### * data-txt,pdf,excel,csv can be opened using pandas
 > 1.can accessing rows and columns
 2.convert the data into csv
 3.csv write back to file
 4.looping a data
 5.adding columns and rows
 6.deleting columns and rows
 7.displays a tabular content
     data analysis and priew

> Pandas-it shows the series object oriented---single dimensional array
2.Dataframe object oriented -------two dimensional array

In [182]:
import pandas

In [183]:
dir(pandas)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [187]:
#Generate a series dataframe object oriented
import pandas as pd
d=[1,45,6,7,9]
d1=["x","y","z"]
x=pd.Series(d)
u=pd.Series(d1)
print(x)
print(u)

0     1
1    45
2     6
3     7
4     9
dtype: int64
0    x
1    y
2    z
dtype: object


In [190]:
#Generate a series dataframe object oriented with indexby using sclarinput
import pandas as pd
d=[1,45,6,7,9]
d1=["x","y","z"]
i=['a','b','c']
x=pd.Series(d)
u=pd.Series(d1,index=i)  #index value
print(x)
print(u)

0     1
1    45
2     6
3     7
4     9
dtype: int64
a    x
b    y
c    z
dtype: object


In [191]:
#Generate a series dataframe object oriented by using dictorianies
import pandas as pd
d={"key1":56,"key2":89,"key3":55}
x=pd.Series(d) #index value
print(x)


key1    56
key2    89
key3    55
dtype: int64


In [192]:
#By using n dimensional array
import pandas as pd
d=[[1,2,3],[4,6,9]]
print(pd.Series(d))

0    [1, 2, 3]
1    [4, 6, 9]
dtype: object


In [193]:
#By using n dimensional array
import pandas as pd
d=[[1,2,3],[4,6,9]]
print(pd.Series(d,index=[1,2]))

1    [1, 2, 3]
2    [4, 6, 9]
dtype: object


In [194]:
#Data frame object orienented with the scalar data
d=[1,6,7,8]
x=pd.DataFrame(d)
x

0
0  1
1  6
2  7
3  8

In [197]:
#Generate a series dataframe object oriented with indexby using sclarinput
import pandas as pd
d=[1,45,6,7,9]
d1=["x","y","z"]

x=pd.DataFrame(d)
u=pd.DataFrame(d1)  #index value
print(x)
print(u)

    0
0   1
1  45
2   6
3   7
4   9
   0
0  x
1  y
2  z


In [198]:
#using dictionaries
x={'x':[3,7,90],'y':[6,90,8],'z':[1,2,4]}
df=pd.DataFrame(x)
df

x   y  z
0   3   6  1
1   7  90  2
2  90   8  4

In [201]:
#using dictionaries
x={'rank1':[3,7,90],'rank2':[6,90,8],'rank3':[1,2,4]}
i="name1","name2","name3"
df=pd.DataFrame(x,index=i)
df

rank1  rank2  rank3
name1      3      6      1
name2      7     90      2
name3     90      8      4

In [206]:
#By using n dimensional array
import pandas as pd
d=[[1,2,3],[4,6,9]]
r=(pd.DataFrame(d,index=["rank1","rank2"],columns=["name1","name2","name3"]))
r

name1  name2  name3
rank1      1      2      3
rank2      4      6      9

In [209]:
import numpy
d=(numpy.random.rand(2,3))
d
r=pd.DataFrame(d,columns=['c1','c2','c3'])
r

c1        c2        c3
0  0.174094  0.108057  0.908375
1  0.074177  0.346099  0.753006

In [212]:
r.columns #columns getting

Index(['c1', 'c2', 'c3'], dtype='object')

In [250]:
#Read a csv file
y="income.csv"
u=pd.read_csv(y)
u

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [215]:
u.columns

Index(['GEOID', 'State', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013'],
      dtype='object')

In [216]:
r=pd.DataFrame(u)
r

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [217]:
r.columns

Index(['GEOID', 'State', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013'],
      dtype='object')

In [221]:
#accessing columns 
for i in u.columns:
    print(i)


GEOID
State
2005
2006
2007
2008
2009
2010
2011
2012
2013


In [222]:
u

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [223]:
u.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 62993, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [231]:
u[["2005"]]

2005
0  37150
1  55891
2  45245
3  36658
4  51755

In [235]:
u[["2012"]] # To get specific column value

2012
0  43464
1  63648
2  47044
3  39018
4  57020

In [234]:
u.loc[2]  #To get single row

GEOID    04000US04
State      Arizona
2005         45245
2006         46657
2007         62993
2008         46914
2009         45739
2010         46896
2011         48621
2012         47044
2013         50602
Name: 2, dtype: object

In [237]:
#Accessing elements in rows rows=itertuples(),iterrow(),iteritems()
for i in u.iterrows():
    print(i)

(0, GEOID    04000US01
State      Alabama
2005         37150
2006         37952
2007         42212
2008         44476
2009         39980
2010         40933
2011         42590
2012         43464
2013         41381
Name: 0, dtype: object)
(1, GEOID    04000US02
State       Alaska
2005         55891
2006         56418
2007         62993
2008         63989
2009         61604
2010         57848
2011         57431
2012         63648
2013         61137
Name: 1, dtype: object)
(2, GEOID    04000US04
State      Arizona
2005         45245
2006         46657
2007         62993
2008         46914
2009         45739
2010         46896
2011         48621
2012         47044
2013         50602
Name: 2, dtype: object)
(3, GEOID    04000US05
State     Arkansas
2005         36658
2006         37057
2007         40795
2008         39586
2009         36538
2010         38587
2011         41302
2012         39018
2013         39919
Name: 3, dtype: object)
(4, GEOID     04000US06
State    California
2005    

In [238]:
for i in df.iterrows():
    print(i)

('name1', rank1    3
rank2    6
rank3    1
Name: name1, dtype: int64)
('name2', rank1     7
rank2    90
rank3     2
Name: name2, dtype: int64)
('name3', rank1    90
rank2     8
rank3     4
Name: name3, dtype: int64)


### delete and addition of columns and rows
for delete 
> Column-pop,del-------- row-drop

In [241]:
#delete column
u.pop("2011")

0    42590
1    57431
2    48621
3    41302
4    53367
Name: 2011, dtype: int64

In [251]:
# delete row
u.drop(3)

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
4  57020  57528

In [254]:
#Addition of column
new={"k1":98,"k2":88,"k3":90,}
print(pd.DataFrame(p,index=[1,2,3]))
new=[1,2,3]
p['z']=new
print(pd.DataFrame(p))


   k1  k2  k3
1  98  88  90
2  98  88  90
3  98  88  90
   k1  k2  k3  z
1  98  88  90  1
2  98  88  90  2
3  98  88  90  3
